apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: devops-cc2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: devops-cc2/api:latest
        ports:
        - containerPort: 8080