apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: devops-cc2
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer 
